import 'bootstrap/dist/css/bootstrap.min.css';

import { Card, Col, Row } from 'reactstrap';
import { useEffect, useState } from 'react';

import { Chip } from '@mui/material';
import Head from 'next/head';
import Image from 'next/dist/client/image';
import Navigation from '../../components/Navigation';
import VerticalTab from '../../components/verticalTab';
import axios from 'axios';
import styles from '../../styles/user.module.scss';

export default function BookingsPage() {
	let userData = {};
	if (typeof window !== 'undefined') {
		// Perform localStorage action
		userData = JSON.parse(localStorage.getItem('userData'));
	}
	const [data, setData] = useState([]);
	useEffect(() => {
		axios
			.get(`/api/booking/${userData.id}/user`)
			.then((res) => {
				console.log(res.data.data);
				setData(res.data.data);
			})
			.catch((err) => {
				console.log(err);
			});
	}, []);

	return (
		<>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<VerticalTab>
				<h1 className={styles.heading}>Bookings</h1>
				<div>
					{data.map((item) => (
						<Card
							key={item.id}
							className={styles.eventCard}
							style={{ padding: '20px', marginBottom: '20px' }}
						>
							<Row>
								<Col md={3}>
									<Image
										src={`/${item.image}`}
										// layout='responsive'
										width={200}
										height={150}
									/>
								</Col>
								<Col md={9} className={styles.eventData}>
									<h6 className={styles.eventName}>{item.event_name}</h6>
									<p className={styles.price}>AED {item.price}</p>
									<p className={styles.description}>{item.description}</p>
									<Row>
										<Col md={3}>
											<p className={styles.eventDetail}>{item.venue}</p>
										</Col>
										<Col md={3}>
											<p className={styles.eventDetail}>{item.audience}</p>
										</Col>
										<Col md={2}>
											<p className={styles.eventDetail}>{item.date}</p>
										</Col>
										<Col md={4}>
											<Chip
												style={{ width: '150px' }}
												label='Paid'
												color='success'
											/>
										</Col>
									</Row>
								</Col>
							</Row>
						</Card>
					))}
				</div>
			</VerticalTab>
		</>
	);
}
