import 'bootstrap/dist/css/bootstrap.min.css';

import Footer from '../../components/Footer';
import Head from 'next/head';
import Navigation from '../../components/Navigation';
import UserEventComponent from '../../components/users/events';
import VerticalTab from '../../components/verticalTab';
import { useContext } from 'react';

export default function UserEvents() {
	const authContext = useContext(AuthContext);
	React.useEffect(() => {
		// checks if the user is authenticated
		authContext.isUserAuthenticated()
			? router.push('/user/profile')
			: router.push('/');
	}, []);

	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<div>
				<VerticalTab>
					<UserEventComponent />
				</VerticalTab>
			</div>
			{/* <Footer /> */}
		</div>
	);
}
