import 'bootstrap/dist/css/bootstrap.min.css';

import Footer from '../../components/Footer';
import Head from 'next/head';
import Navigation from '../../components/Navigation';
import SmallMenu from '../../components/users/smallMenu';
import UserEventComponent from '../../components/users/events';
import VerticalTab from '../../components/verticalTab';
import { useContext } from 'react';

export default function UserEvents() {
	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<div>
				<VerticalTab>
					<SmallMenu />
					<UserEventComponent />
				</VerticalTab>
			</div>
			{/* <Footer /> */}
		</div>
	);
}
