import 'bootstrap/dist/css/bootstrap.min.css';

import { Button, Col, Row } from 'reactstrap';

import Head from 'next/head';
import Image from 'next/dist/client/image';
import Navigation from '../../../components/Navigation';
import UserEventComponent from '../../../components/users/events';
import VerticalTab from '../../../components/verticalTab';
import axios from 'axios';
import styles from '../../../styles/user.module.scss';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function EventDetails() {
	const router = useRouter();
	const [data, setData] = useState({});
	useEffect(() => {
		axios
			.get(`/api/events/${router.query.id}`)
			.then((res) => {
				setData(res.data.data[0]);
				console.log(res.data);
			})
			.catch((err) => {
				console.log(err);
			});
	}, [router.query.id]);
	const handleCancel = () => {
		router.push('/user/events');
	};
	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<div>
				<VerticalTab>
					{Object.keys(data).length > 0 && (
						<div class='container'>
							<Row>
								<Col md={9}>
									<Image src={`/${data.image}`} width={700} height={300} />
									<br />
									<div style={{ marginTop: '10px' }}>
										<h3>{data.name}</h3>
										<p className={styles.price}>AED {data.price}</p>
										<p>{data.description}</p>
									</div>
									<Row>
										<Col md={4}>
											<p className={styles.eventDetail}>{data.venue}</p>
										</Col>
										<Col md={4}>
											<p className={styles.eventDetail}>{data.audience}</p>
										</Col>
										<Col md={4}>
											<p className={styles.eventDetail}>{data.date}</p>
										</Col>
									</Row>
									<div style={{ marginTop: '12px' }}>
										<Button className={styles.buyTicketButton}>
											BUY TICKET
										</Button>
										<Button
											className={styles.cancelEventButton}
											onClick={handleCancel}
										>
											CANCEL
										</Button>
									</div>
								</Col>
							</Row>
						</div>
					)}
				</VerticalTab>
			</div>
			{/* <Footer /> */}
		</div>
	);
}
