import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import ContactForm from '../components/contact';
import Footer from '../components/Footer';
import GalleryMainComponent from '../components/Gallery';
import GoogleMap from '../components/Map';
import Head from 'next/head';
import Header from '../components/Header';
import HeadingComponent from '../components/Heading';
import Navigation from '../components/Navigation';
import ReadyBanner from '../components/ReadyBanner';

export default function GalleryComponent() {
	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<Header title='Gallery' member='' members='' />
			<GalleryMainComponent />
			<ReadyBanner />
			<GoogleMap />
			<HeadingComponent
				heading='Enquiry'
				subHeading='We would like to listen'
				subBoldHeading='from you'
			/>
			<ContactForm />
			<Footer />
		</div>
	);
}
