import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'aos/dist/aos.css';

import { Dialog, DialogActions, DialogTitle } from '@mui/material';

import AOS from 'aos';
import { Button } from 'reactstrap';
import ContactForm from '../components/contact';
import FoodCategory from '../components/Interests/food';
import Footer from '../components/Footer';
import GoogleMap from '../components/Map';
import Head from 'next/head';
import Header from '../components/Header';
import HeadingComponent from '../components/Heading';
import Image from 'next/image';
import InterestsCategories from '../components/Interests';
import KFCPage from '../components/Interests/kfc';
import Navigation from '../components/Navigation';
import styles from '../styles/Interest.module.scss';
import { useState } from 'react';

export default function Interests() {
	const [category, setCategory] = useState('');
	const [foodRes, setFoodRes] = useState('');
	const [comingSoon, setComingSoon] = useState(false);
	const handleComingSoon = () => {
		setComingSoon(!comingSoon);
	};
	const handleFood = () => {
		handleComingSoon();
		// setCategory('food');
	};
	const handleFoodRes = () => {
		setFoodRes('kfc');
	};
	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<Header title='Interests' member='' members='' />
			<br />
			<br />
			{/* Categoris */}

			{category !== 'food' && foodRes == '' && (
				<>
					<HeadingComponent
						heading='Enjoy Promotions'
						subHeading='Lets'
						subBoldHeading='Choose your Interests'
					/>
					<br />
					<br />
					<InterestsCategories handleFood={handleFood} />
				</>
			)}

			{/* {category === 'food' && foodRes == '' && (
				<>
					<HeadingComponent
						heading='Enjoy Promotions'
						subHeading='Lets'
						subBoldHeading='Enjoy Your Meal'
					/>
					<br />
					<br />
					<FoodCategory handleFoodRes={handleFoodRes} />
				</>
			)}
			{foodRes !== '' && (
				<div>
					<HeadingComponent
						heading='Promotions By'
						subHeading=''
						subBoldHeading=''
					/>
					<KFCPage />
					<br />
					<br />
				</div>
			)} */}

			<GoogleMap />
			<HeadingComponent
				heading='Enquiry'
				subHeading='We would like to listen'
				subBoldHeading='from you'
			/>
			<ContactForm />
			<Footer />
			<Dialog
				open={comingSoon}
				onClose={handleComingSoon}
				// fullWidth
				style={{ padding: '36px' }}
				aria-labelledby='alert-dialog-title'
				aria-describedby='alert-dialog-description'
			>
				<DialogTitle className={styles.interestModal}>
					{/* <strong style={{ zIndex: '999', color: '#fda700' }}> */}
					Wonderful brands and offers coming soon!
					{/* </strong> */}
				</DialogTitle>
				<DialogActions
					className='text-center'
					style={{ justifyContent: 'center', paddingBottom: '24px' }}
				>
					<Button
						className={styles.interestModalButton}
						onClick={handleComingSoon}
					>
						Cancel
					</Button>
				</DialogActions>
			</Dialog>
		</div>
	);
}
