import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'aos/dist/aos.css';

import { Dialog, DialogActions, DialogTitle } from '@mui/material';

import AOS from 'aos';
import { Button } from 'reactstrap';
import ContactForm from '../components/contact';
import FoodCategory from '../components/Interests/food';
import Footer from '../components/Footer';
import GoogleMap from '../components/Map';
import Head from 'next/head';
import Header from '../components/Header';
import HeadingComponent from '../components/Heading';
import Image from 'next/image';
import InterestsCategories from '../components/Interests';
import KFCPage from '../components/Interests/kfc';
import Navigation from '../components/Navigation';
import axios from 'axios';
import styles from '../styles/Interest.module.scss';
import { useState } from 'react';

export default function Interests() {
	const [menu, setMenu] = useState([]);
	const [foodRes, setFoodRes] = useState([]);
	const [comingSoon, setComingSoon] = useState(false);
	const [promotion, setPromotion] = useState({});
	const handleComingSoon = () => {
		setComingSoon(!comingSoon);
	};
	const handleFood = (item) => {
		console.log('item', item);
		setPromotion(item);
		axios.get(`/api/brands/${item.id}/category`).then((res) => {
			console.log(res.data.data);
			if (res.data.data.length > 0) {
				console.log(res.data.data);
				setFoodRes(res.data.data);
			} else {
				handleComingSoon();
			}
		});
	};
	const handleMenu = (item) => {
		console.log('item', item);
		axios.get(`/api/deals/${item.id}/brand`).then((res) => {
			console.log(res.data.data);
			if (res.data.data.length > 0) {
				console.log(res.data.data);

				setMenu(res.data.data);
			} else {
				handleComingSoon();
			}
		});
	};
	const handleDeal = () => {
		handleComingSoon();
	};
	console.log('Promotion', promotion);
	return (
		<div>
			<Head>
				<title>Zes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<Header title='Interests' member='' members='' />
			<br />
			<br />
			{/* Categoris */}
			{foodRes.length == 0 && (
				<>
					<HeadingComponent
						heading='Enjoy Promotions'
						subHeading='Lets'
						subBoldHeading='Choose your Interests'
					/>
					<br />
					<br />
					<InterestsCategories handleFood={handleFood} />
				</>
			)}
			{foodRes.length > 0 && menu.length === 0 && (
				<div>
					<HeadingComponent
						heading='Brands Of'
						subHeading={promotion.name}
						subBoldHeading=''
					/>

					<FoodCategory data={foodRes} handleClick={handleMenu} />
					<br />
					<br />
				</div>
			)}
			{menu.length > 0 && (
				<>
					<HeadingComponent
						heading='Enjoy Promotions'
						subHeading='Lets'
						subBoldHeading='Enjoy your deal'
					/>
					<br />
					<br />
					<KFCPage data={menu} handleClick={handleDeal} />
				</>
			)}
			<GoogleMap />
			<HeadingComponent
				heading='Enquiry'
				subHeading='We would like to listen'
				subBoldHeading='from you'
			/>
			<ContactForm />
			<Footer />
			<Dialog
				open={comingSoon}
				onClose={handleComingSoon}
				// fullWidth
				style={{ padding: '36px' }}
				aria-labelledby='alert-dialog-title'
				aria-describedby='alert-dialog-description'
			>
				<DialogTitle className={styles.interestModal}>
					{/* <strong style={{ zIndex: '999', color: '#fda700' }}> */}
					Wonderful brands and offers coming soon!
					{/* </strong> */}
				</DialogTitle>
				<DialogActions
					className='text-center'
					style={{ justifyContent: 'center', paddingBottom: '24px' }}
				>
					<Button
						className={styles.interestModalButton}
						onClick={handleComingSoon}
					>
						Cancel
					</Button>
				</DialogActions>
			</Dialog>
		</div>
	);
}
