import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import ClientSatisfaction from '../components/WhyZes/clientSatisfaction';
import EventManagementSolutions from '../components/WhyZes/eventManagementSolutions';
import Footer from '../components/Footer';
import GoogleMap from '../components/Map';
import Head from 'next/head';
import Header from '../components/Header';
import LifeWithWithoutZes from '../components/WhyZes/index';
import Navigation from '../components/Navigation';
import ReadyBanner from '../components/ReadyBanner';
import TestimonialComponent from '../components/Testimonial';

export default function WhyZes() {
	return (
		<div>
			<Head>
				<title>Res</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<Header title='Why Zes' member='' members='' />
			<LifeWithWithoutZes />
			<EventManagementSolutions />
			<ClientSatisfaction />
			<ReadyBanner />
			<TestimonialComponent />
			<GoogleMap />
			<Footer />
		</div>
	);
}
